# .travis.yml file for LeanCheck
sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

ghc:
  #- "8.0"
  #- "7.10"
  - "7.8"

matrix:
  include:
    - ghc: '7.6'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock HADDOCKFLAGS=
    - ghc: '7.4'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock HADDOCKFLAGS=
# see: https://docs.haskellstack.org/en/stable/travis_ci/
    - addons:
      apt:
        sources:  hvr-ghc
        packages: ghc-7.10.1
      before-install: export PATH=/opt/ghc/head/bin:$PATH
    - addons:
      apt:
        sources:  hvr-ghc
        packages: ghc-head
      before-install: export PATH=/opt/ghc/head/bin:$PATH

script:
  - make && make test && make haddock HADDOCKFLAGS=
  - cabal test

notifications:
  email:
    on_failure: change
