# .travis.yml file for LeanCheck
sudo: true

language: haskell

ghc:
  - "8.0"
  - "7.10"
  - "7.8"

matrix:
  include:
    - ghc: '7.6'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas"
    - ghc: '7.4'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas"

before_install:
  - sudo apt-get install ghc-dynamic

script:
  - make && make test
  - cabal test

notifications:
  email:
    on_failure: change
