# .travis.yml file for LeanCheck
sudo: false

language: haskell

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal

ghc:
  #- "8.0"
  #- "7.10"
  - "7.8"

matrix:
  include:
    - ghc: '7.6'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock HADDOCKFLAGS=
    - ghc: '7.4'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock HADDOCKFLAGS=
# see: https://docs.haskellstack.org/en/stable/travis_ci/
# see: https://github.com/hvr/multi-ghc-travis
    - ghc: '7.10'
      addons:
        apt:
          sources:  hvr-ghc
          packages: [cabal-install-1.22,ghc-7.10.1]
      before_install:
        - export PATH=/opt/ghc/7.10.1/bin:/opt/cabal/1.22/bin:$PATH
        - ghc --version
    - ghc: 'head'
      addons:
        apt:
          sources:  hvr-ghc
          packages: [cabal-install-head,ghc-head]
      before_install:
        - export PATH=/opt/ghc/head/bin:/opt/cabal/head/bin:$PATH
        - ghc --version

script:
  - make && make test && make haddock HADDOCKFLAGS=
  - cabal test

notifications:
  email:
    on_failure: change
