# .travis.yml file for LeanCheck
sudo: false

language: haskell

ghc:
  #- "8.0"
  #- "7.10"
  - "7.8"

matrix:
  include:
    - ghc: '7.6'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock
    - ghc: '7.4'
      script: >
        make      GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make test GHCFLAGS="-fno-warn-unrecognised-pragmas" &&
        make haddock

script:
  - make && make test && make haddock
  - cabal test

notifications:
  email:
    on_failure: change
